// R14 behavior/real-canvas regression suite. No browser or CSS layout engine.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const {createCanvas,Image}=require('@napi-rs/canvas');
const path=require('path');
const {DEFAULT_TARGET,registerR14Fonts}=require('./r14_test_support.cjs');
const targetPath=path.resolve(process.argv[2]||DEFAULT_TARGET);
const source=fs.readFileSync(targetPath,'utf8');
const fontRegistration=registerR14Fonts(source);
function boot(opts={}){
 let clock=1760000000000,timeoutSeq=0;const timeouts=new Map(),intervals=[],listeners={},els=new Map(),store=new Map(Object.entries(opts.storage||{}));
 class Element{constructor(id){this.id=id;this.style={};this.dataset={};this.hidden=['modal','placementBar'].includes(id);this.innerHTML='';this.textContent='';this.scrollTop=0;this.clientWidth=opts.width||390;this.clientHeight=opts.height||844;this.classList={add(){},remove(){},toggle(){}};this.children=new Proxy({},{get:(o,k)=>o[k]||(o[k]=new Element("child"))});this.events={};}addEventListener(n,f){this.events[n]=f;}getBoundingClientRect(){return {x:0,y:0,left:0,top:0,right:this.clientWidth,bottom:this.clientHeight,width:this.clientWidth,height:this.clientHeight};}setAttribute(n,v){this[n]=v;}appendChild(){}insertBefore(){}replaceChildren(){}remove(){}focus(){document.activeElement=this;}click(){}closest(){return null;}setPointerCapture(){}releasePointerCapture(){}}
 function el(s){if(!els.has(s)){const e=new Element(s.replace('#',''));if(s==='#scene'||s==='#minimap'){const cv=createCanvas(s==='#scene'?(opts.width||390):190,s==='#scene'?(opts.height||844):115);e.getContext=(...a)=>cv.getContext(...a);e._canvas=cv;Object.defineProperty(e,'width',{get:()=>cv.width,set:v=>cv.width=v});Object.defineProperty(e,'height',{get:()=>cv.height,set:v=>cv.height=v});e.toDataURL=(...a)=>cv.toDataURL(...a);}els.set(s,e);}return els.get(s);}
 const document={hidden:false,activeElement:null,contains:()=>true,body:new Element('body'),querySelector:el,querySelectorAll(s){if(s==='.countdown'){const ms=[...el('#sheetBody').innerHTML.matchAll(/class="countdown" data-end="([^"]+)"/g)];return ms.map(m=>{const e=new Element('timer');e.dataset.end=m[1];return e;});}return [];},createElement(tag){return tag==='canvas'?createCanvas(1,1):new Element(tag);},addEventListener(n,f){(listeners[n] ||= []).push(f);}};
 const FakeDate=class extends Date{constructor(...a){super(...(a.length?a:[clock]));}static now(){return clock;}};
 const window={addEventListener(n,f){listeners[n]=[f];}},context={window,document,Image,HTMLElement:Element,Date:FakeDate,localStorage:{getItem:k=>store.get(k)||null,setItem(k,v){if(opts.failStorage)throw Error('QuotaExceededError');store.set(k,v);}},console,innerWidth:opts.width||390,performance:{now:()=>0},ResizeObserver:class{constructor(f){this.f=f;}observe(){}},requestAnimationFrame:f=>1,cancelAnimationFrame(){},setTimeout(f){const n=++timeoutSeq;timeouts.set(n,f);return n;},clearTimeout:n=>timeouts.delete(n),setInterval(f){intervals.push(f);return intervals.length;},clearInterval(){},Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}},Math};context.globalThis=context;vm.createContext(context);
 const hook=`window.TEST={get state(){return state},set state(v){state=v},get modal(){return modalView},get pendingImport(){return pendingImport},get placement(){return placement},get started(){return started},baseState,validState,plant,buy,feed,water,speed,harvest,beginCraft,collectCraft,workshopJobs,bulkFill,bulkCare,bulkPanel,regionPanel,cellPanel,bagPanel,workshopPanel,farmStatus,guidePanel,settingsPanel,beginPlacement,confirmPlacement,cancelPlacement,candidates,handle,updateCountdowns,close,open,recoverEnergy,persist,applyImport,zoomAt,overview,focusPoint,render,resize,drawMini,metrics,get camera(){return camera}};`;
 let scripts=[...source.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]);scripts[scripts.length-1]=scripts.at(-1).replace(/\nboot\(\);/,hook+'\nwindow.bootPromise=boot();');scripts.forEach(s=>vm.runInContext(s,context));
 return {context,api:window.TEST,els,store,listeners,document,advance:n=>clock+=n,async ready(){await window.bootPromise;assert(window.TEST.started,'asset boot failed: '+window.TEST.metrics.errors.join(','));},flush(){const entries=[...timeouts.values()];timeouts.clear();entries.forEach(f=>f());},tick(){intervals.forEach(f=>f());},render(path){window.TEST.resize();window.TEST.overview();window.TEST.render(1000);fs.writeFileSync(path,el('#scene')._canvas.toBuffer('image/png'));},clock:()=>clock};
}
async function run(){const h=boot();await h.ready();const t=h.api;let tests=0;function check(name,fn){fn();tests++;console.log('PASS',name);}function fresh(){t.state=t.baseState();t.close();}
 check('All embedded active art loads and initial save validates',()=>{assert(t.metrics.assets>0,'no embedded runtime images loaded');assert(t.validState(JSON.parse(JSON.stringify(t.state))));});
 check('Occupied/invalid workshop slot never consumes materials',()=>{fresh();t.beginCraft('feed',0);const n=t.state.inventory.wheat;t.beginCraft('feed',0);assert.equal(t.state.inventory.wheat,n);t.beginCraft('feed',-1);assert.equal(t.state.inventory.wheat,n);});
 check('Two jobs run in parallel, early/repeated collection is safe',()=>{fresh();t.beginCraft('feed',0);t.beginCraft('fertilizer',1);assert(t.workshopJobs()[0]);t.collectCraft(0);assert.equal(t.state.stats.crafted,0);h.advance(7000);t.collectCraft(0);const n=t.state.inventory.feed;t.collectCraft(0);assert.equal(t.state.inventory.feed,n);assert.equal(t.state.stats.crafted,1);});
 check('Workshop expansion adds real slots; save roundtrip keeps all jobs',()=>{fresh();t.beginPlacement('workshop');t.confirmPlacement();assert.equal(t.workshopJobs().length,4);t.beginCraft('feed',2);assert(t.workshopJobs()[2]);assert(t.validState(JSON.parse(JSON.stringify(t.state))).jobs[2]);});
 check('Cancel and repeated expansion do not double-charge; 100 dynamic regions',()=>{fresh();const coins=t.state.coins;t.beginPlacement('veg','veg');t.cancelPlacement();assert.equal(t.state.coins,coins);t.state.coins=1e9;for(let i=0;i<100;i++){t.beginPlacement(['veg','flowers','orchard','ranch','fishery','special'][i%6]);t.confirmPlacement();}const count=t.state.regions.length,c=t.state.coins;t.confirmPlacement();assert.equal(t.state.coins,c);assert.equal(count,110);assert.equal(new Set(t.state.regions.map(r=>r.gx+':'+r.gy)).size,count);assert(t.validState(JSON.parse(JSON.stringify(t.state))));});
 check('Same district expansions stay attached to own district',()=>{fresh();t.beginPlacement('veg','veg');assert(t.placement.options.every(q=>t.state.regions.find(r=>r.id===q.parent).districtId==='veg'));});
 check('Bulk planting is atomic and double-click safe',()=>{fresh();const r=t.state.regions.find(r=>r.id==='veg'),empty=r.cells.filter(c=>!c.entity).length,c=t.state.coins;t.bulkFill('veg','wheat');assert.equal(t.state.coins,c-empty*16);const c2=t.state.coins;t.bulkFill('veg','wheat');assert.equal(t.state.coins,c2);assert(r.cells.every(c=>c.entity));});
 check('Wrong family and unaffordable batch cannot mutate inventory or coins',()=>{fresh();const before=JSON.stringify(t.state);t.bulkFill('veg','lotus');assert.equal(JSON.stringify(t.state),before);t.state.coins=0;const before2=JSON.stringify(t.state);t.bulkFill('veg','wheat');assert.equal(JSON.stringify(t.state),before2);});
 check('Single plant → water once → offline maturity → harvest once',()=>{fresh();t.plant('veg-1','carrot');const e=t.state.regions.find(r=>r.id==='veg').cells[1].entity;t.water('veg-1');const end=e.endsAt,en=t.state.energy;t.water('veg-1');assert.equal(t.state.energy,en);assert.equal(e.endsAt,end);h.advance(9000);assert(t.harvest('veg-1'));const n=t.state.inventory.carrot;assert(!t.harvest('veg-1'));assert.equal(t.state.inventory.carrot,n);});
 check('Perennial survives harvest; whole batch care consumes once',()=>{fresh();const r=t.state.regions.find(r=>r.id==='orchard');for(const c of r.cells)if(c.entity){c.entity.endsAt=h.clock()-1;t.harvest(c.id,true);}const n=r.cells.filter(c=>c.entity?.hungry).length;t.state.inventory.fertilizer=1;const c=t.state.coins;t.bulkCare('orchard');assert.equal(t.state.coins,c-(n-1)*12);assert.equal(t.state.inventory.fertilizer,0);assert(r.cells.filter(c=>c.entity).every(c=>!c.entity.hungry));t.bulkCare('orchard');assert.equal(t.state.coins,c-(n-1)*12);});
 check('Animals repeat production and fish clear pond after catch',()=>{fresh();t.buy('ranch-1','cow');h.advance(15000);t.harvest('ranch-1');assert(t.state.regions.find(r=>r.id==='ranch').cells[1].entity.hungry);t.feed('ranch-1');const feed=t.state.inventory.feed;t.feed('ranch-1');assert.equal(t.state.inventory.feed,feed);t.buy('fishery-1','salmon');t.feed('fishery-1');const f=t.state.inventory.feed;t.feed('fishery-1');assert.equal(t.state.inventory.feed,f);h.advance(20000);assert(t.harvest('fishery-1'));assert.equal(t.state.regions.find(r=>r.id==='fishery').cells[1].entity,null);});
 check('Energy regenerates by elapsed minutes and never exceeds 40',()=>{fresh();t.state.energy=5;h.advance(125000);assert.equal(t.recoverEnergy(),2);assert.equal(t.state.energy,7);t.recoverEnergy();assert.equal(t.state.energy,7);h.advance(24*3600000);t.recoverEnergy();assert.equal(t.state.energy,40);});
 check('Legacy v3 fields migrate and region sequence is repaired',()=>{fresh();t.state.coins=1e8;t.beginPlacement('veg');t.confirmPlacement();const s=JSON.parse(JSON.stringify(t.state));s.seq=0;s.level=0;delete s.stats.mined;delete s.stats.animalCollects;delete s.energyUpdatedAt;delete s.savedAt;s.jobs=undefined;s.job={recipe:'feed',startedAt:h.clock(),endsAt:h.clock()+6000};t.state=t.validState(s);assert.equal(t.state.level,28);assert.equal(t.state.stats.mined,0);assert(t.state.seq>=1);t.beginPlacement('flowers');t.confirmPlacement();assert(t.validState(JSON.parse(JSON.stringify(t.state))));});
 check('Reject missing mandatory region, inherited catalog key and misplaced cells',()=>{fresh();let s=JSON.parse(JSON.stringify(t.state));s.regions=s.regions.filter(r=>r.id!=='ranch');assert.throws(()=>t.validState(s));s=JSON.parse(JSON.stringify(t.state));s.jobs[0]={recipe:'constructor',endsAt:1,startedAt:1};assert.throws(()=>t.validState(s));s=JSON.parse(JSON.stringify(t.state));s.regions.find(r=>r.id==='veg').cells[0].x+=1;assert.throws(()=>t.validState(s));});
 check('Countdown updates region readiness but cannot override newer panel',()=>{fresh();const r=t.state.regions.find(r=>r.id==='veg');r.cells.forEach(c=>{if(c.entity)c.entity.endsAt=h.clock()+1000;});t.regionPanel('veg');assert(h.els.get('#sheetBody').innerHTML.includes('countdown'));h.advance(2000);t.updateCountdowns();t.bagPanel();h.flush();assert.equal(t.modal,'bag');t.regionPanel('veg');assert(h.els.get('#sheetBody').innerHTML.includes('收取本区（7）'));t.close();h.flush();assert.equal(t.modal,null);});
 check('UI routes render without errors',()=>{fresh();for(const route of ['module-hub','more','settings','map','book','farm-status','guide','workshop','home','weather','companion','trade','build','expand']){t.handle(route,{});assert(h.els.get('#sheetTitle').textContent);}t.handle('region-open',{id:'flowers'});assert.equal(t.modal,'region');});
 fresh();h.render(path.join(__dirname,'render-r14-390x844.png'));check('Real canvas renderer runs at portrait viewport',()=>assert.equal(t.metrics.errors.length,0));
 const q=boot({failStorage:true});await q.ready();check('Storage refusal leaves game running and visibly warns',()=>{assert.equal(q.api.persist(),false);assert.equal(q.els.get('#saveBadge').textContent,'未保存');});
 const p=boot({storage:{'ice-homestead-pixel-v3':'bad JSON'}});await p.ready();check('Unrecognised save remains untouched',()=>{p.api.persist();assert.equal(p.store.get('ice-homestead-pixel-v3'),'bad JSON');});
 console.log(JSON.stringify({passed:tests,assets:t.metrics.assets,renderer:'@napi-rs/canvas, NO BROWSER LAYOUT',target:targetPath,fontRegistration,savedVersion:t.state.version},null,2));
}
if(require.main===module)run().catch(e=>{console.error(e);process.exit(1)});module.exports={boot,source,targetPath,fontRegistration};
